//Modul Users
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"Agung",
    "email":"agung@gmail.com",
    "password":"12345678",
    "confPassword": "12345678",
    "role":"user"
}

###
GET http://localhost:5000/users

###
GET http://localhost:5000/users/1670670b-f96e-49ad-8534-a7ec5dc3e3a5

###
PATCH http://localhost:5000/users/3f38de36-572e-429d-84df-8ae3e1cd1763
Content-Type: application/json

{
    "name":"Zulfahmi",
    "email":"zulfahmi22@gmail.com",
    "password":"",
    "confPassword": "",
    "role":"user"
}

###
DELETE  http://localhost:5000/users/3f38de36-572e-429d-84df-8ae3e1cd1763

###
//Login Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"abiihutabarat29@gmail.com",
    "password":"12345678"
}

###
//Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"agung@gmail.com",
    "password":"12345678"
}

###
GET http://localhost:5000/me

###
DELETE http://localhost:5000/logout


//Modul Product
###
GET http://localhost:5000/products

###
POST http://localhost:5000/products
Content-Type: application/json

{
      "name":"Kaos Kaido",
      "price":110000
}

###
GET http://localhost:5000/products

###
GET http://localhost:5000/products/94e19e2d-df75-4aa1-8829-a853c50fe381

###
PATCH  http://localhost:5000/products/b0764cb1-9f76-4a58-a57a-a0c8b11a8255
Content-Type: application/json

{
      "name":"Kaos Kaido Updated",
      "price":120000
}

###
DELETE  http://localhost:5000/products/ae5b0e7d-c808-4d04-ac49-8cdf8fb4cf7e


// Modul Instansi
###
POST http://localhost:5000/instansi
Content-Type: application/json

{
    "name":"Dinas Komunikasi dan Informatika"
}

###
GET http://localhost:5000/instansi

###
PATCH http://localhost:5000/instansi/e05532c9-d6a4-49b5-803a-32b3c4c3134b
Content-Type: application/json

{
    "name":"Dinas Pencatatan dan Kependudukan"
}

###
DELETE  http://localhost:5000/instansi/e05532c9-d6a4-49b5-803a-32b3c4c3134b


// Modul Divisi
###
POST http://localhost:5000/division
Content-Type: application/json

{
    "name":"Bidang Informasi Komunikasi Publik",
    "instansiId": 1
}

###
GET http://localhost:5000/division

###
GET http://localhost:5000/division/0f9635ad-997b-4739-8378-3d769f5c90b6

###
PATCH http://localhost:5000/division/0f9635ad-997b-4739-8378-3d769f5c90b6
Content-Type: application/json

{
    "name":"Bidang Informasi Komunikasi Publik",
    "instansiId": 1
}

###
DELETE  http://localhost:5000/division/0f9635ad-997b-4739-8378-3d769f5c90b6
